all:epoll_1 epoll_2 epoll_3 epoll_4 epoll_5 epoll_6 epoll_7

epoll_1:epoll_1.o
	g++ epoll_1.cpp -o epoll_1

epoll_2:epoll_2.o
	g++ epoll_2.cpp -o epoll_2

epoll_3:epoll_3.o
	g++ epoll_3.cpp -o epoll_3

epoll_4:epoll_4.o
	g++ epoll_4.cpp -o epoll_4

epoll_5:epoll_5.o
	g++ epoll_5.cpp -o epoll_5

epoll_6:epoll_6.o
	g++ epoll_6.cpp -o epoll_6

epoll_7:epoll_7.o
	g++ epoll_7.cpp -o epoll_7

clean:
	rm -f epoll_1 epoll_2 epoll_3 epoll_4 epoll_5 epoll_6 epoll_7
	rm -f *.o		
